### ISSUE TITLE
Change the jet selection criteria

### ISSUE THREAD

**Issue by YasuyukiOkumura** [UCATLAS/ZJetBalance#15]
Since we need to apply jet veto something like
pt^{sub leading} < 0.2 \* pT_Z^{ref}, we need to have lower jet information than 20 GeV. 
( /afs/cern.ch/work/o/okumura/public/analysi2015/ZBJetBalance_v5/runscripts )

Yasu will change that and resubmit the jobs after several tests.

**Comment by gfacini** [comment]
I agree keeping only the 1 jet minimum and no explicit maximum on the number of jets.
Maybe we can put the jet pT cut at 15 GeV just to be clean?

**Comment by YasuyukiOkumura** [comment]
Yes, it makes sense. 

https://github.com/UCATLAS/ZJetBalance/blob/master/data/jetSelect.config
Currently I put jet pT = 0, while we only have pT > ~15 GeV in xAOD

Do you know if the Run1 analysis used very low pT for veto purpose? 

Cheers,
Yasu Okumura
