### ISSUE TITLE
weight_xs

### ISSUE THREAD

**Issue by YasuyukiOkumura** [UCATLAS/ZJetBalance#17]
Dear Gabriel, 

Could you please have a look at the following line and check if this way of weight_xs/weight definition is 
implemented on purpose? 
https://github.com/UCATLAS/ZJetBalance/blob/master/Root/BalanceAlgorithm.cxx#L274-L275
I guessed that you would like to divide that value by m_numAMIEvents, 
but could depend on the definition. So please check that. 
If this is not on purpose, I will update that things from my end, 

Best regards,
Yasu Okumura

**Comment by gfacini** [comment]
Hi Yasu,

When submitting to the grid or running in general, sometimes not all the events are processed.
When this happens, dividing by the number in AMI is incorrect.  BasicEventSelection starts a
cutflow and it is the first number in this histogram that is needed to normalize the sample as it
corresponds to all the events processed.

I have the code somewhere else to make sure the cutflow is added to the file where the tree is
written.  I will implement that here as well if you agree.

Cheers,
Gabriel

**Comment by YasuyukiOkumura** [comment]
OK, I agree with you. 

Also I found that we need to use sometimes number MC events and some times 
unweighted MC event numbers, (e.g. Powheg inclusive sample case, we need to check weighted number of events, but not raw count), so it would be good not to apply this scale in MiniTree production level.

PS:
In the current analysis chain, I am checking the cut-flow histogram (either of weighted for Powheg sample case) and the final normalization is given by that. (i.e. so that it is normalized with respect to the MC stat which are really used in grid)

Cheers,
Yasu
