### ISSUE TITLE
First plots!

### ISSUE THREAD

**Issue by YasuyukiOkumura** [UCATLAS/ZJetBalance#19]
Dear Gabriel, 

Here is a set of first plot from 63pb (C3/C4)

The tree is available on eos:
- /eos/atlas/user/o/okumura/data/ZBJetBalanceStudy_v20150722/data15_13TeV
- /eos/atlas/user/o/okumura/data/ZBJetBalanceStudy_v20150722/mc15_50ns/ZmumuPowhegPythia8

The first plots are available at:
- https://okumura.web.cern.ch/okumura/tmp/matometeDraw.pdf

Note : MC is normalized with respect to cross section for all plots.
p1 : pT(Z) after all selection criteria (up to dPhi(jet, Z)<2.8) are applied
p2 : M(Z) after all selection criteria applied
p3 : validation plots : dPhi after all selection criteria applied
p4 : general validation plots : N_{jets} after preselection (tree creation stage) for jets with pT>30 GeV
p5 : general validation plots : jet eta after preselection for jets with pT>30 GeV
p5 : general validation plots : jet pT distribution after preselection for jets with pT>30 GeV
p7 : validation plots : <mu> distribution after all selection applied 
p8 - p11 : balance plots in each phase space 
p12 : mean of the balance distribution (given by fit by a Poissonian distribution) as a function of pT in a certain eta slice (this time, we have only one eta bin anyway. We could have more eta binning with higer stat)
p13 : width of them given by a fit
p14-p21 similarly mean & width for a function of eta for each pT slice (again currently we only have one eta bin, so as a function of eta does not make sense very much so far)

As we saw, there are several things to check more.
The current framework should be a good starting point to have a closure and serious look! 

NOTE:
The following procedure I took for the plots:

The final test plotter macro is not included in the package, and you may get it with

```
wget https://okumura.web.cern.ch/okumura/tmp/forGabriel/matometeDraw.C
```

then using the executable in the package I ran the algorithm over the given MiniTree, 
and ran the fitter over the histograms 

```
# analyze Z+jets MiniTree
runProcessZJetBalanceMiniTree  -inFile /eos/atlas/user/o/okumura/data/ZBJetBalanceStudy_v20150722/mc15_50ns/ZmumuPowhegPythia8/ -submitDir submitDir3
rm -f zall.root
hadd zall.root submitDir3/hist-*.root*
# run JES_Response_Fitter over the given histograms in analysis over tree 
ZJetBalancePlotter -inFile  /afs/cern.ch/work/o/okumura/public/analysi2015/ZBJetBalance_v5/runscripts/zall.root -usePoisson -outTag zall

# analyze data MiniTree
runProcessZJetBalanceMiniTree  -inFile /eos/atlas/user/o/okumura/data/ZBJetBalanceStudy_v20150722/data15_13TeV/ -submitDir submitDir4
rm -f dataall.root
hadd dataall.root submitDir4/hist-*.root*
# run JES_Response_Fitter over the given histograms in analysis over tree 
ZJetBalancePlotter -inFile  /afs/cern.ch/work/o/okumura/public/analysi2015/ZBJetBalance_v5/runscripts/dataall.root -usePoisson -outTag dataall

# run final plotter using the output files given by the processes above
# ZJetBalancePlotterOutzall.root, ZJetBalancePlotterOutdataall.root
# zall.root, dataall.root

root -l -q -b 'matometeDraw.C+(0.062556, true)' # luminosity in fb-1
```

Thanks for your time / consideration. Let's have fun for coming things! 

Best regards,
Yasu Okumura

**Comment by gfacini** [comment]
Yasu, can we put the plotting macro into git?

**Comment by YasuyukiOkumura** [comment]
Sure I will work on it tonight. 
I will add them in the utils as executable.

**Comment by YasuyukiOkumura** [comment]
.. Time limit today. I will work on that tomorrow, sorry for pending it.

**Comment by YasuyukiOkumura** [comment]
done
