### ISSUE TITLE
Derivation

### ISSUE THREAD

**Issue by gfacini** [UCATLAS/ZJetBalance#24]
We need one...now!

**Comment by gfacini** [comment]
@YasuyukiOkumura 

We found MC - either SUSY2 or SUSY5 would work but we are not sure about the statement about the object based skimming here:

https://twiki.cern.ch/twiki/bin/view/AtlasProtected/SUSYxAODDerivationsr20#20_1_5_7

To be on the safe side, SUSY2 might be better which requires 2 leptons about 9 GeV.

Taking this as a good way forward we have MC:

mc15_13TeV.361106.PowhegPythia8EvtGen_AZNLOCTEQ6L1_Zee.merge.DAOD_SUSY2.e3601_s2576_s2132_r6630_r6264_p2375/
mc15_13TeV.361107.PowhegPythia8EvtGen_AZNLOCTEQ6L1_Zmumu.merge.DAOD_SUSY2.e3601_s2576_s2132_r6630_r6264_p2375/
mc15_13TeV.361108.PowhegPythia8EvtGen_AZNLOCTEQ6L1_Ztautau.merge.DAOD_SUSY2.e3601_s2576_s2132_r6630_r6264_p2375/

and data:

#C2
data15_13TeV.00270806.physics_Main.merge.DAOD_SUSY2.f611_m1463_p2375/
data15_13TeV.00270953.physics_Main.merge.DAOD_SUSY2.f611_m1463_p2375/
data15_13TeV.00271048.physics_Main.merge.DAOD_SUSY2.f611_m1463_p2375/
#C3
data15_13TeV.00271298.physics_Main.merge.DAOD_SUSY2.f611_m1463_p2375/
data15_13TeV.00271388.physics_Main.merge.DAOD_SUSY2.f611_m1463_p2375/
data15_13TeV.00271421.physics_Main.merge.DAOD_SUSY2.f611_m1463_p2375/
#C4
data15_13TeV.00271516.physics_Main.merge.DAOD_SUSY2.f611_m1463_p2375/
data15_13TeV.00271595.physics_Main.merge.DAOD_SUSY2.f611_m1463_p2375/
#C5
data15_13TeV.00271744.physics_Main.merge.DAOD_SUSY2.f611_m1463_p2384/

Let's do the work to get these into the package with the correct cross sections etc and then submit!!!

Brian & Gabriel

**Comment by YasuyukiOkumura** [comment]
Dear Brian & Gabriel, 

Great! 

Do you know the meaning of "Calibrated Jet" in the first line? 
If you have not done the test run over some data and MC samples, could you please do that? 

Feel free for the modification in the Ntuplizer code running over the DxADOs in case of needs.
( I am working on the MiniTree analyzer and Plotter macro so should be no interference! )

Thanks a lot. 

Regards,
Yasu Okumura

**Comment by YasuyukiOkumura** [comment]
I ran a test and 
In the SUSY derivation we do not have "JetEMScaleMomentum", then the running will crash. 

Here are two solutions. (I prefer 2) if you are happy with it. )

Option 1)  
Remove "scales" from JetDetailStr in ZJetBalance/data/zjetAlgo.config.
We will miss the following branches in the MiniTree by this configuration: 

```
m_tree->Branch("jet_emScalePt",              &m_jet_emPt            );
m_tree->Branch("jet_pileupScalePt",          &m_jet_pileupPt        );
m_tree->Branch("jet_originConstitScalePt",   &m_jet_originConstitPt );
m_tree->Branch("jet_etaJESScalePt",          &m_jet_etaJESPt        );
m_tree->Branch("jet_gscScalePt",             &m_jet_gscPt           );
m_tree->Branch("jet_insituScalePt",          &m_jet_insituPt        );
```

Option 2) 
have a patch for xAODAnaHelpers/Root/HelpTreeBase.cxx
Just comment out the line below

```
//m_jet_emPt.push_back( jet_itr->getAttribute<xAOD::JetFourMom_t>( "JetEMScaleMomentum" ).Pt() / m_units )
```

**Comment by btuan** [comment]
/eos/atlas/user/b/btuan/data

**Comment by YasuyukiOkumura** [comment]
Dear Brian,

Could you please change the file permission?
https://twiki.cern.ch/twiki/bin/view/AtlasComputing/ATLASStorageAtCERN#Permissions_on_your_personal_are

Best regards,
Yasu Okumura

On Thu, Aug 6, 2015 at 5:36 PM, btuan notifications@github.com wrote:

> /eos/atlas/user/b/btuan/data
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UCATLAS/ZJetBalance/issues/24#issuecomment-128412338.

## 

University of Chicago - CERN - ATLAS

**Comment by btuan** [comment]
Hi Yasu,

Oops! I thought I set it properly....Just changed it. Could you try and let me know if it works?

Best,
Brian

**Comment by YasuyukiOkumura** [comment]
No, it did not but it is OK (I also have a few test samples.)

PS:
I also have a few samples for testing. At least the it works fine in MC.
Once I test it on data as well, I will start the submission.

On Thu, Aug 6, 2015 at 5:49 PM, btuan notifications@github.com wrote:

> Hi Yasu,
> 
> Oops! I thought I set it properly....Just changed it. Could you try and
> let me know if it works?
> 
> Best,
> Brian
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UCATLAS/ZJetBalance/issues/24#issuecomment-128416130.

## 

University of Chicago - CERN - ATLAS

**Comment by btuan** [comment]
@YasuyukiOkumura,

OK, I should have just reset the permissions to 755 for the entire data
directory recursively -- if it still doesn't work, I'll take a closer look
when I come in tomorrow!

Best,

Brian
