### ISSUE TITLE
error in compilation

### ISSUE THREAD

**Issue by YasuyukiOkumura** [UCATLAS/ZJetBalance#26]
Dear Gabriel, 

Have you seen the following compilation error when we start from scratch? 
I used 20.3.18 for this compilation in order to have proper Isolation tool used. 
It is related to the MuonTriggerScaleFactor compilation. 

If you have any experience, please let me know that. Otherwise, I will see more details for that. 

/afs/cern.ch/work/o/okumura/public/analysi2015/ZBJetBalance_v6/xAODAnaHelpers/Root/MuonEfficiencyCorrector.cxx: In member function ‘virtual EL::StatusCode MuonEfficiencyCorrector::initialize()’:
/afs/cern.ch/work/o/okumura/public/analysi2015/ZBJetBalance_v6/xAODAnaHelpers/Root/MuonEfficiencyCorrector.cxx:254:25: error: ‘class CP::MuonTriggerScaleFactors’ has no member named ‘setRunNumber’
   if( m_muonTrigSFTool->setRunNumber( m_runNumber ) == CP::CorrectionCode::Error ) {
                         ^

**Comment by gfacini** [comment]
Hi Yasu,

I was using 2,3,21 and things worked just fine.  Can you try that release?
I updated the TWiki to reflect the change.

Cheers,
Gabriel

**Comment by YasuyukiOkumura** [comment]
Dear Gabriel, 

Thanks a lot! Yes, it works (compilation and test run of executable) with 2.3.21. 
Great!

Best regards,
Yasu Okumura
