### ISSUE TITLE
Muon in Jet Correction

### ISSUE THREAD

**Issue by gfacini** [UCATLAS/ZJetBalance#3]
Select the muon
dR<0.4 of jet
quality cuts: Tight (double check)
pT>4 GeV
e loss in calo 
Follow idea of Hbb https://twiki.cern.ch/twiki/bin/viewauth/AtlasProtected/BjetcorrectionrecipeCracow
code line 8195:
https://svnweb.cern.ch/trac/atlasinst/browser/Institutes/CERN/ElectroweakBosons/trunk/AnalysisWZorHbb/src/WZorHbb.cxx

**Comment by YasuyukiOkumura** [comment]
Done! Please close this issue. (I cannot close this issue somehow)
