### ISSUE TITLE
pileup reweighting configuration file

### ISSUE THREAD

**Issue by YasuyukiOkumura** [UCATLAS/ZJetBalance#30]
Dear Gabriel and Brian, 

Pileup configuration for Z mumu sample has been completed and stored in ZJetBalance/data/

Although, as a backup, we may use the Zmumu ones, 
I just launched the pileup reweighting configuration generation 
- z ee
  http://bigpanda.cern.ch/task/6203333/
- z tautau
  http://bigpanda.cern.ch/task/6203329/

**Comment by gfacini** [comment]
Hi Yasu,

Are these ready?  If so we should turn on pileup RW in the configs.

Gabriel

**Comment by YasuyukiOkumura** [comment]
It running. ee has been done, tautau is still running.

By the way, I would like to mention that we can do the pileup reweighting in the MiniTree analysis level,  https://github.com/UCATLAS/ZJetBalance/blob/master/Root/ProcessZJetBalanceMiniTree.cxx#L623-L630 so that we may calculate that in local analysis level with whatever configuration. 
Therefore we may go ahead for the submission without waiting this completion! 

Best regards,
Yasu Okumura

**Comment by btuan** [comment]
Added PRW file for Zee in newest version. Waiting on Ztautau PRW file, as soon as [SARA site](http://waniotest.appspot.com) comes back online. File here: `data/prw.361106.e3601_a766_a767_r6264.v00_METADATA.root`.

**Comment by btuan** [comment]
@YasuyukiOkumura 

Could you retry the PRW file for the 361108 Ztautau sample? The task submission state is listed as "finished" with a few incomplete tasks.

http://bigpanda.cern.ch/jobs/?jeditaskid=6203333&display_limit=100 

Best,
Brian

Edit: not "broken" but "finished", mea culpa.

**Comment by YasuyukiOkumura** [comment]
Thanks, it has been started to retry. 
( at least 98% completion is enough level to apply to the pileup reweighting tool in case it does not come available in time ) 

TTbar configuration file is available here (done): 
http://bigpanda.cern.ch/task/6223935/

**Comment by btuan** [comment]
@YasuyukiOkumura 

Thanks! Yeah, I uploaded the TTbar merged prw file to `data/` yesterday evening! Should be ready to go.

Best,
Brian
