### ISSUE TITLE
Output Electron scale factors into tree

### ISSUE THREAD

**Issue by btuan** [UCATLAS/ZJetBalance#35]
@YasuyukiOkumura 

I will implement this in the next day, and it should be ready by end of tomorrow. I should run it with PRW, yes?

Best,
Brian

**Comment by YasuyukiOkumura** [comment]
PRW = pileup reweighting? 
The pileup reweighting may run in the analysis in MiniTree level, so do not need to run it! 

Best regards,
Yasu Okumura

**Comment by btuan** [comment]
Ok, sounds good.

Brian
