### ISSUE TITLE
Submission status

### ISSUE THREAD

**Issue by YasuyukiOkumura** [UCATLAS/ZJetBalance#37]
Dear all, 

The submission is not started yet. 
The plan is 
- Electron part, we found that the electron scale factor is not properly added in the MiniTree and Brian will work on that a bit
- Muon part, we found that the btag information is not properly set in the MiniTree in the data case (details will follow)

( Although we may start the submission only for MC, rather 
  I would like to wait for Gabriel's green light for software )

Dear Gabriel, 

Could you please test the data files (This is not really for ZJetBalance, but xAH related things.)? 
/afs/cern.ch/user/o/okumura/public/workspace/data/data15_13TeV.00271516.physics_Main.merge.DAOD_SUSY2.f611_m1463_p2375_tid05968506_00/DAOD_SUSY2.05968506._000067.pool.root.1

After testing and several checks, I believe that we need to modify 
https://github.com/UCATLAS/xAODAnaHelpers/blob/master/Root/BJetEfficiencyCorrector.cxx

As far as I understood, the problem is as following. 
- the isBTag decision was done in this class for MC and data
- on the other hand, this "Efficiency Correction Tool" is designed to run only on the MC
- Then, the isBTag is not properly set in the output. 

I think you need to modify at least the following two functions:
- initialize() function to call the configure() function and instantiate BTaggingSelectionTool properly even for data
- execute() function to set IsBTag flag properly even for data

Could you please have a look and update the software? 
( Maybe I missed some side effect. ) 

After your green light, I will start the submission with the modified version. 

PS:
Also if I ran on the data sample shown above,  we have the following messages.

```
Warning in <StatusCode>:
Warning in <StatusCode>: Unchecked status codes encountered during the job
Warning in <StatusCode>: Number of unchecked successes: 22372
Error in   <StatusCode>: Number of unchecked failures: 127
Warning in <StatusCode>: To fail on an unchecked code, call StatusCode::enableFailure() at the job's start
Warning in <StatusCode>:
```

( The xAH software needs to be modified to check all the return status code properly )

Best regards,
Yasu Okumura

**Comment by YasuyukiOkumura** [comment]
I will be offline for a few hours from now on.

**Comment by gfacini** [comment]
Hi Yasu,

What do you think about these changes:
https://github.com/UCATLAS/xAODAnaHelpers/commit/89f32095b10c0de55f231e9cfd436186f84b26a4

Cheers,
Gabriel

**Comment by btuan** [comment]
@YasuyukiOkumura @gfacini 

Tested changes are here for electronSF:
https://github.com/UCATLAS/xAODAnaHelpers/compare/electronSF

Best,
Brian

**Comment by YasuyukiOkumura** [comment]
Dear Gabriel, 

Thanks a lot! It seems fine with me. 
I will test the latest version of software and submit. 

Dear Brian, 

Thanks for the update! 
( I did not have time to check carefully in hope that xAH team has a careful look at it!  )

Best regards,
Yasu Okumura

**Comment by YasuyukiOkumura** [comment]
I tested the whole chain with the very latest software and it seems fine! 
I will start the submission for muon MC / data soon!

**Comment by YasuyukiOkumura** [comment]
Launched!

You may find the job status in my panda page:
http://bigpanda.cern.ch/user/Yasuyuki%20Okumura/?display_limit=200
or on each job summary page. 

Z MC
- mc15_13TeV.361107.PowhegPythia8EvtGen_AZNLOCTEQ6L1_Zmumu.merge.DAOD_SUSY2.e3601_s2576_s2132_r6630_r6264_p2375/ : http://bigpanda.cern.ch/task/6217576/
- mc15_13TeV.361108.PowhegPythia8EvtGen_AZNLOCTEQ6L1_Ztautau.merge.DAOD_SUSY2.e3601_s2576_s2132_r6630_r6264_p2375/ : http://bigpanda.cern.ch/task/6217589/

C2
- data15_13TeV.00270806.physics_Main.merge.DAOD_SUSY2.f611_m1463_p2375/ : http://bigpanda.cern.ch/task/6217540/
- data15_13TeV.00270953.physics_Main.merge.DAOD_SUSY2.f611_m1463_p2375/ : http://bigpanda.cern.ch/task/6217542/
- data15_13TeV.00271048.physics_Main.merge.DAOD_SUSY2.f611_m1463_p2375/ : http://bigpanda.cern.ch/task/6217544/

C3
- data15_13TeV.00271298.physics_Main.merge.DAOD_SUSY2.f611_m1463_p2375/ : http://bigpanda.cern.ch/task/6217547/
- data15_13TeV.00271388.physics_Main.merge.DAOD_SUSY2.f611_m1463_p2375/ : http://bigpanda.cern.ch/task/6217550/
- data15_13TeV.00271421.physics_Main.merge.DAOD_SUSY2.f611_m1463_p2375/ : http://bigpanda.cern.ch/task/6217552/

C4
- data15_13TeV.00271516.physics_Main.merge.DAOD_SUSY2.f611_m1463_p2375/ : http://bigpanda.cern.ch/task/6217554/
- data15_13TeV.00271595.physics_Main.merge.DAOD_SUSY2.f611_m1463_p2375/ : http://bigpanda.cern.ch/task/6217556/

C5
- data15_13TeV.00271744.physics_Main.merge.DAOD_SUSY2.f611_m1463_p2384/ : http://bigpanda.cern.ch/task/6217558/

**Comment by gfacini** [comment]
AWESOME!!!!

GREAT WORK ALL AROUND =)
Enjoy Friday night a little =)

**Comment by btuan** [comment]
@YasuyukiOkumura @gfacini 

Ah! Great, I submitted as well. One of my jobs with the TTreeCache enabled had scouting fail, so I resubmitted just in case with it off as well.

I submitted both Z->ee and Z->mumu lepton choices for data and MC. The relevant output tags are:
v1 and v0.1 with TTreeCache
v2 without TTreeCache.
v3 without submitter stupidity.

http://bigpanda.cern.ch/user/Brian%20Tuan/?display_limit=100

Happy Friday!
Brian

**Comment by btuan** [comment]
This is odd! It seems that for both Yasu and me, data run 271595 is broken. But otherwise, everything else works fine!

**Comment by YasuyukiOkumura** [comment]
Dear Brian, 

Try the following option and resubmit that. 
driver.options()->setString (EL::Job::optSubmitFlags, "--forceStaged");

**Comment by btuan** [comment]
@YasuyukiOkumura 

Okay, just resubmitted -- thanks!

Best,
Brian

**Comment by YasuyukiOkumura** [comment]
Here is the first plots from muons analysis. 

The instruction of how to plot it can be seen below (with the latest update) : 

https://okumura.web.cern.ch/okumura/v20150807/drawZJetBalanceOutput.pdf
- p1-p3 ;Z kinematics after all selection applied
- p4-p9 : muon kinematics after all selection applied
- p10-p15 : jet kinematics after all selection applied (pT > 30 GeV, eta<2.5)
- p16 : validation plot mu (all events in MiniTree)
- p17 : N jets (all events in MiniTree)
- p18 - p21 : jet kinematics (all events in MiniTree)

How to plot them, 

```
runProcessZJetBalanceMiniTree -inFile /eos/atlas/user/o/okumura/data/ZBJetBalanceStudy_v20150807/mc15_13TeV_50ns/mc15_13TeV_50ns_361107 -submitDir submitDirZMC

runProcessZJetBalanceMiniTree -inFile /eos/atlas/user/o/okumura/data/ZBJetBalanceStudy_v20150807/data15_13TeV_50ns -submitDir submitDirData

rm -f ZmumuAll.root
hadd ZmumuAll.root submitDirZMC/hist-user*.root

rm -f DataAll.root
hadd DataAll.root submitDirData/hist-user*.root

#dxAOD skimming efficiency = 9881474/19962997 = 4.949895e-01
drawZJetBlanace -d DataAll.root -m ZmumuAll.root -l 0.0783190 -w -a 4.949895e-01

```

**Comment by gfacini** [comment]
Yasu - this is great!! For the preselection it seems the ttbar will fill in the gaps nicely

**Comment by gfacini** [comment]
Once the submission is done and we have a nice set of plots lets close down this milestone and start building one for the 1st presentation

**Comment by YasuyukiOkumura** [comment]
Dear Gabriel and Brian, 

Here is the updated results: 
- https://okumura.web.cern.ch/okumura/v20150812/output.pdf
- https://okumura.web.cern.ch/okumura/v20150812/table.pdf

The number of Z+jets events have a good consistency between MC and Data.
While the jet multiplicity has higher in data, therefore 
if I plot the all jet (pT>30 GeV), data has some excess than MC. 
( To avoid the confusion in the presentation, I plotted the "leading jet" distribution instead. )

I will have more plot for the jet balance and response function things tomorrow for the muon channel

Best regards,
Yasu Okumura

**Comment by gfacini** [comment]
Yasu,

This is great!

The normalization difference of 13% is a little outside
the lumi error of 10%.

I see a shape in the eta distribution of the muons and
the jets.  The jets is from the eta-intercalibration correction
not being applied (this will be the official recommendation
next week or something like that).  This confirms the
idea to do the balance in bins of jet detector eta.

∆φ(Z, jet) is the has the largest difference in efficiency.
For that plot we should take the absolute value of phi
and restrict the range to see what is happening before
the cut.

Lets see the electron plots!!!

Cheers,
Gabriel

**Comment by YasuyukiOkumura** [comment]
The latest results, using the eta binning with detector eta and Run1 binning definition. 
- validation plots https://okumura.web.cern.ch/okumura/v20150813/output.pdf
- jet response function plots https://okumura.web.cern.ch/okumura/v20150813/output2.pdf (given by a Poissonian fit)

Best regards, 
Yasu Okumura
