### ISSUE TITLE
Trigger cut to be applied

### ISSUE THREAD

**Issue by YasuyukiOkumura** [UCATLAS/ZJetBalance#40]
Dear Brian, 

In the latest pull request, I modified configuration file for basic selection 
so that we will apply trigger cut in the analysis. 

Could you please resubmit the electron channel with the latest version of configuration files
by pulling the latest version of matser branch ?

Best regards,
Yasu Okumura

**Comment by btuan** [comment]
Hello Yasu,

Thank you for bringing this to light...I will submit this as soon as
possible! I'm with my family for this evening, but I will get to this by
tomorrow afternoon at the latest.

Best,
Brian

**Comment by btuan** [comment]
Hello @YasuyukiOkumura 

All submitted! Just one error:

```
Command:
['prun', '--rootVer=6.02/12', '--cmtConfig=x86_64-slc6-gcc48-opt', '--nGBPerJob=MAX', '--nFilesPerJob=2', '--mergeOutput', '--exec=runjob.sh data15_13TeV.00271595.physics_Main.merge.DAOD_SUSY2.f611_m1463_p2375', '--mergeScript=elg_merge jobdef.root %OUT %IN', '--inDS=data15_13TeV.00271595.physics_Main.merge.DAOD_SUSY2.f611_m1463_p2375/', '--outDS=user.btuan.data15_13TeV.00271595.physics_Main.Zeev4', '--outputs=hist-output.root,cutflow.root,metadata.root,tree.root', '--writeInputToTxt=IN:input.txt', '--match=*', '--useRootCore', '--forceStaged', '--inTarBall=jobcontents.tgz']
failed with return code  90
output was:
INFO : upload source files
INFO : submit
ERROR : task submission failed. jediTaskID=6217897 is in the broken state for outDS=user.btuan.data15_13TeV.00271595.physics_Main.Zeev4/. You can re-execute the task with the same or another input once it goes into finished/failed/done
```

But this is the dataset that we were having issues with earlier, so, the problem likely isn't in the code.

Best,
Brian

**Comment by YasuyukiOkumura** [comment]
Dear Brian, 

See below: 

You need to submit the jobs with different output DS. 
( The panda is smart to know which input data has been used for the output DS 
  so that it can avoid using the same input file twice in the same output DS)

Therefore if you want to run it from scratch, you need to change the output DS name. 
You may do that with something like: 

```
runZBJetBalance -inFile mc15_13TeV_grid.txt -outputTag muon.v20150807.03
```

PS: 

Also please pull my latest request, where I change the cross section values. 
With the newer one, please submit a job for ttbar as well
- mc15_13TeV.410004.PowhegHerwigppEvtGen_UEEE5_ttbar_hdamp172p5_nonallhad.merge.DAOD_SUSY2.e3836_a766_a767_r6264_p2375/

**Comment by btuan** [comment]
Hi Yasu,

The output tag should not be an issue -- I iterate the version number for each run (and if the problem were in the output DS name, the other jobs would not have submitted). I just submitted the ttbar sample with the updated k-factored cross sections with output tag Zeev5.

Best,
Brian

**Comment by YasuyukiOkumura** [comment]
Dear Brian,

But this error message said that
you already have user.btuan.data15_13TeV.00271595.physics_Main.Zeev4 and it
has been in broken state.

ERROR : task submission failed. jediTaskID=6217897 is in the broken
state for outDS=user.btuan.data15_13TeV.00271595.physics_Main.Zeev4/.
You can re-execute the task with the same or another input once it
goes into finished/failed/done

So it at least saying that you are submitting with the already existing
output DS names.
(and especially this one is in broken state), For the V5, please make sure
that you used very new dataset name
and your job started from scratch.

Best regards,
Yasu Okumura

On Sun, Aug 9, 2015 at 11:52 AM, btuan notifications@github.com wrote:

> Hi Yasu,
> 
> The output tag should not be an issue -- I iterate the version number for
> each run (and if the problem were in the output DS name, the other jobs
> would not have submitted). I just submitted the ttbar sample with the
> updated k-factored cross sections with output tag Zeev5.
> 
> Best,
> Brian
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UCATLAS/ZJetBalance/issues/40#issuecomment-129148676.

## 

University of Chicago - CERN - ATLAS

**Comment by btuan** [comment]
@YasuyukiOkumura 

Ah! Apologies, I found the error -- it was a reused output tag. I resubmitted and it went through cleanly. Thanks for your help.

Best,
Brian
