### ISSUE TITLE
Scale factors not in tree.

### ISSUE THREAD

**Issue by btuan** [UCATLAS/ZJetBalance#51]
Neither muon nor electron trigger scale factors are in the trees! Not sure why, but debugging now.

Also, in my branch called `Brian` I added a command-line flag `-limitEvents` followed by an integer to limit the number of events iterated through by EventLoop for testing purposes.

**Comment by YasuyukiOkumura** [comment]
FYI: 
At least what I submitted on Friday had reasonable scale factor.

```
root -l root://eosatlas//eos/atlas/user/o/okumura/data/ZBJetBalanceStudy_v20150807/mc15_13TeV_50ns/mc15_13TeV_50ns_361107/user.okumura.mc15_13TeV.361107.PowhegPythia8EvtGen_AZNLOCTEQ6L1_Zmumu.muon.v20150807.01_tree.root/all.root
```

Best regards,
Yasu Okumura

**Comment by btuan** [comment]
@YasuyukiOkumura 

Apologies, this was due to a confusion of mine of scale factors in data vs in MC. The electron trigger weight is not properly filled, but everything else checks out okay.

Best,
Brian
