### ISSUE TITLE
cutflow

### ISSUE THREAD

**Issue by YasuyukiOkumura** [UCATLAS/ZJetBalance#53]
Dear Brian & Gabriel, 

Could you please check the following?

I think the cutflow given by the BalanceAlgorithm has inconsistent label 
between cutflow and cutflow_weighted. I did not have time to check, 
and if you have time could you please have a look and modify that?

Thanks, 

Best regards, 
Yasu Okumura

**Comment by btuan** [comment]
@YasuyukiOkumura 

Yes, I noticed this too! It is fixed with [this commit](https://github.com/UCATLAS/ZJetBalance/commit/8a39c72703d4c231c6af656fe6a2dab4e05f7d74).

Best,
Brian

**Comment by YasuyukiOkumura** [comment]
Dear Brian, 

Thanks! OK I will close this ticket. 

Best regards,
Yasu Okumura
