### ISSUE TITLE
Electron plots

### ISSUE THREAD

**Issue by YasuyukiOkumura** [UCATLAS/ZJetBalance#55]
Dear Brian, 

Did you already download the latest version of the electron channel data?
If yes, could you please let me know after the adjustment, 
so that I will run the plotter chain for the electron channels as well ?

I will update the plotter code and upload script to run the chain for plots. 

Best regards,
Yasu Okumura

**Comment by btuan** [comment]
Hi @YasuyukiOkumura,

I am working on this right now! There seem to be a few bugs (some branches are being properly filled when code is tested locally but not on grid, for some reason), and as soon as I figure out what's going wrong with that, I will send you my results! I have been updating the processing chain as well (in branch ZJetBalance/Brian) and I just added many of the updated branches for b-tagged jets and electrons today (and two functions `IsMC()` and `isMuonSample` to streamline the analysis a bit further).

Best,
Brian

Edit: the code in my branch is committed and pushed online, but it's not ready to run out-of-the-box yet! Currently encountering some segfaults that I'm working through.

**Comment by YasuyukiOkumura** [comment]
OK Thanks for the information. 
Please post when it has been done!

**Comment by btuan** [comment]
@YasuyukiOkumura,

The error was due to a clash in naming of the MiniTree for this analysis and that for DijetResonance (the package was in my work directory and unused by this analysis). I suspect the reason why your analysis went through was because you did not have DijetResonanceAlgo checked out at the time. 

I have updated the include guards in our code to prevent that from having an adverse affect on GRID jobs in the future! Everything is now re-running on the grid with output tag `Zee20150813v7`. I will update you as soon as this is done!

Best,
Brian

**Comment by YasuyukiOkumura** [comment]
nice catch!

**Comment by gfacini** [comment]
Indeed ! not a simple one =)

**Comment by btuan** [comment]
@YasuyukiOkumura @gfacini ,

I'm waiting on the GRID job to finish now, but I took the incomplete MC sample and plotted it -- just to make sure that all the code works as intended. I have linked the first set of plots (incomplete) [here](http://faxbox.usatlas.org/user/btuan/drawZJetBalanceOutput.pdf). 

The GRID job should finish running by tomorrow morning, and I will be able to access the internet briefly before I get on the train, so I will run all of the plots before I leave for the weekend. I will have internet access Friday, Saturday, and Sunday, so I can make more plots as requested! I have pushed the latest version of my code to GitHub, and that has been tested to work. 

The data files and ttbar samples have been collected and are in `/afs/cern.ch/work/b/btuan/public/output/mcttbar/all.root` and `/afs/cern.ch/work/b/btuan/public/output/dataZee/all.root`. I will update in the morning on the status of the MC samples (and upcoming plots).

Best,
Brian

Edit: the empty plots in the PDF are of the muon 1 and 2 pT, eta, and phi. I didn't leave them out of the plotting code, but it should be okay!

**Comment by btuan** [comment]
@YasuyukiOkumura @gfacini 

The Ztautau job has not finished yet, but I have run the plotting again with 96% of the final data. The total plot is [here](http://faxbox.usatlas.org/user/btuan/FirstPlots20150814.pdf): as we see, we have a marked deficiency in data (I'm trying to think of reasons why at the moment). I have included the Poisson fits here as well. [First file for data](http://faxbox.usatlas.org/user/btuan/Zjet_DB_Poisson_fits_FitData.pdf). [Second file for MC](http://faxbox.usatlas.org/user/btuan/Zjet_DB_Poisson_fits_FitMCAll.pdf). Please let me know what you think!

Best,
Brian

**Comment by YasuyukiOkumura** [comment]
Great progress.

Did you take the DxAOD skimming efficiency into account?

xAOD = 19890410
DxAOD = 8782611

then you need to apply 0.44155 factor at the end for MC. 

Also could you give me the file path (eos?) I can access from the lxplus, 
so that I can check the distribution in myend as well?

Thanks, 

Best regards,
Yasu

**Comment by btuan** [comment]
@YasuyukiOkumura 

The files are in `/afs/cern.ch/work/b/btuan/public/output` and the entire output from GRID, cutflows and all, are hadded into the respective `all.root` files. I was using the other factor of `4.949895e-01` that you were using for the Zmumu channel. In addition, I hadded together the Zee, Ztautau, and ttbar samples into the `MCAll.root` that I used as the input to the drawing algorithm.

The updated plot with this factor is [here](http://faxbox.usatlas.org/user/btuan/FirstPlots20150814rev2.pdf)

I am having some troubles accessing eos right now, I will try again later, but for now, the processed minitrees are at `/afs/cern.ch/user/b/btuan/work/` in directories `submitData` `submitMCZee` `submitMCttbar` and `submitMCZtautau`. I should have set the permission to the entire work directory to 765, so you should be able to read and write!

Best,
Brian

**Comment by YasuyukiOkumura** [comment]
OK, good. Thanks a lot. I will have a look at the files on afs. 

Please also start the submission jobs with the latest version of the configuration for both MC / data
after fixing the lepton pT selection etc (if you did not start it yet). 
It will be what will be presented in meeting Tuesday as the first solid results. 

Best regards,
Yasu Okumura

**Comment by btuan** [comment]
@YasuyukiOkumura,

This latest v7 revision was submitted with the configuration files as of
yesterday morning -- which to my knowledge is the latest configuration with
the `Gradient` isolation WP and pT criteria, right?

Best,
Brian

**Comment by YasuyukiOkumura** [comment]
YES! Let us know if the files get available.

Another advice for plots:
For the electron plots. also please check if you use the proper luminosity
for normalization.
In your plot, it seems you are using luminosity for muon trigger.

This suggestion reminded me of the needs for update of iLumiCalc input
files.
To be the best precise, I will prepare the iLumiCalc root file with the
exact good run list information for our study
for muon and electron triggers individually.

Best regards,
Yasu Okumura

On Fri, Aug 14, 2015 at 11:06 AM, btuan notifications@github.com wrote:

> @YasuyukiOkumura,
> 
> This latest v7 revision was submitted with the configuration files as of
> yesterday morning -- which to my knowledge is the latest configuration with
> the `Gradient` isolation WP and pT criteria, right?
> 
> Best,
> Brian
> 
> On Fri, Aug 14, 2015, 10:46 AM YasuyukiOkumura notifications@github.com
> wrote:
> 
> > OK, good. Thanks a lot. I will have a look at the files on afs.
> > 
> > Please also start the submission jobs with the latest version of the
> > configuration for both MC / data
> > after fixing the lepton pT selection etc (if you did not start it yet).
> > It will be what will be presented in meeting Tuesday as the first solid
> > results.
> > 
> > Best regards,
> > Yasu Okumura
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/UCATLAS/ZJetBalance/issues/55#issuecomment-131028547
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UCATLAS/ZJetBalance/issues/55#issuecomment-131032854.

## 

University of Chicago - CERN - ATLAS

**Comment by YasuyukiOkumura** [comment]
Dear Brian, 

I am testing the electron data. 
Could you please replace the all.root by just using hadd of all the tree files? 
Is it possible? 

i.e. 
Your file (e.g. /afs/cern.ch/work/b/btuan/public/output/dataZee/all.root) already includes cutflow or cutflow_weighted, renamed from cutflow_RunNumber, and this is out of assumption of the following scripts. 

Thanks, 

Best regards,
Yasu Okumura

**Comment by btuan** [comment]
Hi Yasu,

Ah, of course. I will do this ASAP. I will let you know when this is
finished.

Best,
Brian

**Comment by btuan** [comment]
@YasuyukiOkumura

This is done!

Best,
Brian

**Comment by YasuyukiOkumura** [comment]
OK good. Since we have the first set of electron plots, I am closing this ticket.
