### ISSUE TITLE
Electron preselection 

### ISSUE THREAD

**Issue by YasuyukiOkumura** [UCATLAS/ZJetBalance#66]
Dear Brian, 

I found that in electron preselection, both LH and CB algorithm are required, 
Could you please modify that? 

For this iteration (i.e. first 25ns plots), we do not need to have them, but modify that for next iteration.
https://github.com/UCATLAS/ZJetBalance/blob/master/data/electronPreSelect.config

Best regards,
Yasu Okumura

**Comment by btuan** [comment]
Hi @YasuyukiOkumura 

Fixed in latest push. Thanks!

Best,
Brian
